### ISSUE TITLE
Changes to IDs and FedRAMP Required Content

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#42]
# Action Item

**This is a ...**
  - [ ] **fix** - Something needs to be different.

**This relates to ...**
  - [ ] **General/Overall**

## Describe the problem or enhancement

There are two significant concerns with FedRAMP's current approach of prescribing identifiers for content FedRAMP requires in OSCAL files:
1. This does not maximize cooperation with other compliance frameworks.
1. NIST is considering a change to OSCAL IDs that would require a UUID in most cases. 

For both of the above reasons, FedRAMP must move away from the use of required identifiers, and provide a different machine-readable method for ensuring FedRAMP-required content is present. This new method must not use identifiers, and must co-exist with other frameworks within the same files.

For example, if a system must be authorized for FedRAMP, DoD, and ISO-27001/2, a single SSP should be able to support all three compliance frameworks simultaneously. 

## Goals:

- [ ] Release CSP, 3PAOs and tool developers from the burden of using specific identifiers for FedRAMP compliance items within OSCAL.
- [ ] Ensure a replacement mechanism can co-exist with other compliance frameworks.

## Dependencies:

None

## Acceptance Criteria

- [ ] All [FedRAMP Documents Related to OSCAL Adoption](https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated. 
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

## Other Comments

None.

**Comment by brianrufgsa** [comment]
After consultation with the NIST OSCAL Team, the current plan is to define an OSCAL extension using the ```prop``` field, which will be used to "tag" content as relevant to FedRAMP mandates.

For example, instead of using a ```party``` ID of "csp", the party entry representing the CSP may have any ID, but must have an extra ```prop``` field, tagging it as the party entry providing the FedRAMP-required CSP name and address.

This extra prop field will look similar to the following:
```
<prop name="compliance" ns="https://fedramp.gov/ns/oscal">csp-name</prop>
```
All tagging will use the same ```name``` and ```ns``` flags. The actual value provided will be prescribed by FedRAMP in the FedRAMP OSCAL Registry.

## MINIMUM NECESSARY
This will only be used where FedRAMP-required content is not clear from the OSCAL syntax alone, as defined by the FedRAMP PMO. 

For example, the authorization boundary and data flow diagrams have clear syntax in an OSCAL SSP, thus will not require this tagging.

Unfortunately, without tagging, it can be unclear to automated tools which party is the CSP, 3PAO, ISSO, System Owner, etc.

**Comment by brianrufgsa** [comment]
Current plan is to use "conformity" as the prop name, so the syntax would look like this:

```
<prop name="conformity" ns="https://fedramp.gov/ns/oscal">csp-name</prop>
```

**Comment by ohsh6o** [comment]
Will have to review current state with NIST OSCAL team. It appears this is a rephrasing of one use case for usnistgov/OSCAL#825.

**Comment by ohsh6o** [comment]
Will close this when we release updated guidance docs for 1.0.0, having reviewed current revisions and Brian's notes.

**Comment by brian-ruf** [comment]
Please note this issue is predominantly overtaken by events at this point. 

The guidance documents were transitioned to reflect NIST's ID to UUID shift about a year go, and the April 2020 comment about conformity tags is obsolete. 

Before my departure, @david-waltermire-nist and I worked out other OSCAL mechanisms to account for every place in which conformity tags were used. For example, there is now a recognized `cloud-service-provider` role ID value, and the FedRAMP extension model is supposed to enforce a cardinality of exactly one party assigned to that role. 

I agree with @ohsh6o recommendation to close the issue with the 1.0.0 release.
