### ISSUE TITLE
Show easier syntax for compound paths in Guides?

### ISSUE THREAD

**Issue by wendellpiez** [GSA/fedramp-automation#50]
* **This is a ...**
  - [ ] **concern** - I think something needs to be different.
  - [ ] **question** - I didn't understand something.
  - [x] **kudo** - I found something helpful and want to encourage it in future FedRAMP publications.
  - [x] **request** - I would like to see something additional provided.

* **This relates to ...**
  - [ ] the **FedRAMP OSCAL Registry** (Excel File)
  - [x] the **Guide to OSCAL-based FedRAMP Content** (PDF)
  - [x] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)** (PDF)
  - [x] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)** (PDF)
  - [x] the **Guide to OSCAL-based FedRAMP Security Assessment Reports (SAR)** (PDF)
  - [x] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)** (PDF)
  - [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
  - [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
  - [ ] **General/Overall**
  - [ ] **Other**

* **Where, exactly?**

Throughout the guides, wherever there are compound paths (where predicates contain paths).

* **What is your feedback?**

Wherever long compound paths appear in the registry, instead provide decomposed variants.

Example: System Owner's Name in section 4.6 (for Table 3.1) is (now) shown to be

```xpath
/*/metadata/party[@uuid=[/*/metadata/responsible-party[@role-id="system-owner"]/party-uuid]]/party-name
```

(btw there is also a little bug in there!)

Same thing, decomposed:

```xpath
let $system-owner-assignment := /*/metadata/responsible-party[@role-id="system-owner"]
return /*/metadata/party[@uuid=$system-owner-assignment/party-uuid]/party-name
```

(This is XPath syntax but we could also use English or pseudocode to express the variable binding.)

Or even

```xpath
let $system-owner-assignment := /*/metadata/responsible-party[@role-id="system-owner"]
let $system-owner := /*/metadata/party[@uuid=$system-owner-assignment/party-uuid]
return $system-owner/party-name
```

This would make the paths more intelligible and sensible.

* **What action would you like to see from the FedRAMP PMO?**

Consider whether and how syntax might be further explained and improved on, and execute revisions of the guides accordingly. This info is extremely useful, but as given one has to be more or less an expert in XPath to take advantage of it.

Since as it seems there are also bugs in these paths, perhaps this should all be done systematically, perhaps until the paths themselves can be validated operationally (for example with the help of the XSLT under development).
 
* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. slack, gitter, etc)

n/a

**Comment by wendellpiez** [comment]
```
let $metadata := /*/metadata
let $system-owner-assignment := $metadata/ responsible-party[@role-id="system-owner"]
let $system-owner := $metadata/ party[@uuid=$system-owner-assignment/party-uuid]
return $system-owner/party-name
```

And similarly ...

```
let $ao-assignment := $metadata/ responsible-party[@role-id="authorizing-official"]
let $ao := $metadata/ party[@uuid=$authorizing-official-assignment/party-uuid]
let $ao-name := $authorizing-official/party-name
let $ao-email := $authorizing-official/email
let $ao-phone := $authorizing-official/phone
let $ao-title := $authorizing-official/prop[@name='title'] [@ns='https://fedramp.gov/ns/oscal']
let $ao-agency-name := $metadata/party[@uuid = $ao/member-of-organization]/party-name 
```

**Comment by ohsh6o** [comment]
@wendellpiez, is this what you wanted to discuss in the guides per our conversation last week? Let me know. Thanks in advance for your continued collaboration and cooperation.

**Comment by ohsh6o** [comment]
On Friday, I met with Wendell and 10x developers due to similar and overlapping feedback.

In the context of specific feedback around XPath usage, Wendell proffered feedback around 3 common themes.

- Continue to not use `oscal:` or `o:` namespace prefixes.
- Start making queries more DRY `[@ns="https://fedramp.gov/ns/oscal"]` statements everywhere
- Start removing cardinality argument issues where applicable `/*/control-implementation/implemented-requirement[@control-id="ac-2"]/prop[@name="control-origination"][@ns="https://fedramp.gov/ns/oscal"][1]/@value`
- Start rethinking how we use short-hand explanations like:`Replace "[1]" with "[2]", "[3]", etc.` kind of footnotes that are problematic and hide the important semantic values of example XPath _depending on context_, remove or make clear.

More generally, I will need to work with FedRAMP PMO on determining a just-in-time feedback mechanism about XPath and other programming examples in the guides. I hope with that feedback we determine if XPath is worth maintaining, or deprecating for other content.

More to follow. Will continue work on this issue or close accordingly.

**Comment by ohsh6o** [comment]
Per internal conversations with the PMO, we have decided on leaving the XPath as-is. Long-term approaches to improved feedback mechanisms will come later, and not in time for this release. We will release the FedRAMP OSCAL `fedramp1.0.0-oscal1.0.0` release and adjust XPath examples if we receive feedback through those mechanisms that indicate community interest in significant refactor of XPath examples.
