### ISSUE TITLE
FedRAMP Information Types XML Does Noth Have Prefix fedramp-

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#67]
# Describe the bug

I am not 100% certain this is intentional or not, but when converting the FedRAMP OSCAL Registry from Excel to XML:

- [FedRAMP Values](https://github.com/GSA/fedramp-automation/blob/master/resources/xml/fedramp_values.xml) are enclosed in `<fedramp-values/>`
- [FedRAMP Threats](https://github.com/GSA/fedramp-automation/blob/master/resources/xml/fedramp_threats.xml) are enclosed in `<fedramp-threats/>`
- [FedRAMP Information Types](https://github.com/GSA/fedramp-automation/blob/master/resources/xml/fedramp_information-types.xml) are enclosed in `<infomation-types/>`

Is this intentional?

# Who is the bug affecting?

Ongoing validation tooling in the medium-term future, but not currently impacting me at this time, potentially not others as well.

# What is affected by this bug?

N/A

# When does this occur?

N/A

# How do we replicate the issue?

Review files in Github

If applicable, add screenshots to help explain your problem.}

# Expected behavior (i.e. solution)

Consistency in the trees being prefix with FedRAMP, unless otherwise needed.

# Other Comments

N/A

**Comment by brianrufgsa** [comment]
@ohsh6o Those are actually NIST SP 800-60 information types, which happen to be the only information types recognized by FedRAMP. So while the file name is intended to reflect the information types FedRAMP accepts, I anticipate the structure may be adopted by NIST or others, which is why I avoided using `fedramp-` in the root element name of that file.

That file was created as a convenience so that individual tool developers didn't have to each convert 800-60 content to a machine-readable format in order to display those choices to users.

If anything, perhaps the file name should be changed to better clarify that the information is NIST content, converted to machine-readable format by FedRAMP as a convenience, since FedRAMP is not the content author.

**Comment by ohsh6o** [comment]
OK, sorry that makes some sense. Do you want this closed and/or link to somewhere in the usnistgov/OSCAL issues? Or make one? I actually spent 10 minutes or so looking through the issues with clever keywords, but I cannot recall which issue in that repo was related to this work.

Either way, let us know and I will act accordingly here.

**Comment by ohsh6o** [comment]
Brian's previous comment clarified this issue. I will close this issue.
