### ISSUE TITLE
[Question]: Does index for the validation report start at 0 or 1

### ISSUE THREAD

**Issue by Telos-sa** [GSA/fedramp-automation#956]
### This is a ...

request - need something additional provided

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [ ] the **Guide to OSCAL-based FedRAMP Content**
- [ ] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [ ] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### What is your feedback?

In the error log from the oscal-cli, the schema path of the error is provided like:
/system-security-plan/control-implementation[1]/implemented-requirement[417]/statement[1]/responsible-role[1]

We were wondering if these indices start at 0, or 1?

We also were wondering why some objects have indices such as with 'control-implementation[1]' - there should only ever be one control-implementation element.

### Where, exactly?

- oscal-cli v2.4.0
- OSCAL SSP v1.1.2

**Comment by aj-stein-gsa** [comment]
Thanks for the question, @Telos-sa. This question is important and I am surprised you are the first to ask. Quick answer is that it is 1-indexed, not 0-indexed, details below.

FedRAMP constraints use MetaPath under the hood, and a quick summary of [what that is and where the specification is defined](https://pages.nist.gov/metaschema/specification/syntax/metapath/). The tl;dr is the Metaschema specification and conformant tooling follow the XPath 3.1 specification as closely as possible because changing behavior would mean building derivative documentation, so we want to not duplicate it all.

So for Metapath and XPath 3.1, all sequence lookups are 1-indexed, not 0-indexed. This is not said in one simple sentence, but discussed in some detail as part of dynamic context information [in this section of that specification](https://www.w3.org/TR/xpath-31/#eval_context).

I hope that helps. If this answer does not clarify the validation report info or there is a related feature or bug report you want to add, feel free to reopen this issue.
