### ISSUE TITLE
zero padded control ids mixed with non-padded

### ISSUE THREAD

**Issue by sunstonesecure-robert** [GSA/fedramp-automation#987]
Some of the parameter control IDs have zero padded control IDs, eg ac-01 vs ac-1 and some do not, eg:

https://github.com/GSA/fedramp-automation/blob/c784140bc6d1ac9fa159aabc0e8a29e9aa2c63a9/dist/content/rev5/baselines/yaml/FedRAMP_rev5_HIGH-baseline_profile.yaml#L830

Shouldn't they be consistent?

**Comment by aj-stein-gsa** [comment]
> Shouldn't they be consistent?

Sure, of course. Reviewing the upstream [NIST SP 800-53 Revision 5 catalog, OSCAL version 1.3.0 from the usnistgov/oscal-content repo](https://github.com/usnistgov/oscal-content/blob/v1.3.0/nist.gov/SP800-53/rev5/xml/NIST_SP-800-53_rev5_catalog.xml), those parameters are based on the upstream identifiers (even if they are not defined. By the nature of [profile resolution as defined](https://pages.nist.gov/OSCAL/resources/concepts/processing/profile-resolution/), the FedRAMP profiles must customize by those identifiers, not others.

Would you be willing to open an issue in the [oscal-content repo](https://github.com/usnistgov/oscal-content) to request this alignment and cleanup? If NIST changes the upstream source and releases it, we can use this in our profile resolution process. If you are unclear on required details and how to comprehensively check the prefixing without a lot of manual review, let me know.

Since you posed this issue as a question and I gave the answer above, I will close for now. You can feel free to re-open for help with writing an issue to the upstream repo or when the upstream changes are made to request we adjust our profiles against that catalog.

As always, thanks for working with us and opening these issues.
